# Don't install packages that are less than 12 hours old
# This reduces the risk of installing compromised packages.
# In most cases, malicious releases are discovered and removed from the registry
# within an hour.
# see: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 720

onlyBuiltDependencies:
  - esbuild
